### ISSUE TITLE
Please advise ASAP. my app crashes on Google play

### ISSUE THREAD

**Issue by hisham2007** [stkent/amplify#146]
Dears,
         Thank you for great work. but my app crash on Google play. it doesn't crash with me but crashlytics report this crash for many users:

android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.github.stkent.amplify.prompt.BasePromptView$SavedState

Please advise

**Comment by stkent** [comment]
Thanks for the bug report! Please update the description to include:

- The full stack trace of the crash;
- The version of the library you are currently using.

Once I have this information I'll be able to start investigating!

**Comment by hisham2007** [comment]
version: 1.3.0
affected users: 59 user with 150 crashes
full stack:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tabe3.news/com.tabe3.news.ui.activity.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.github.stkent.amplify.prompt.BasePromptView$SavedState
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.github.stkent.amplify.prompt.BasePromptView$SavedState
       at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
       at android.os.Parcel.readParcelable(Parcel.java:2245)
       at android.view.AbsSavedState.(AbsSavedState.java)
       at android.view.View$BaseSavedState.(View.java)
       at com.github.stkent.amplify.prompt.DefaultLayoutPromptView$SavedState.(DefaultLayoutPromptView.java)
       at com.github.stkent.amplify.prompt.DefaultLayoutPromptView$SavedState$1.createFromParcel(DefaultLayoutPromptView.java:141)
       at com.github.stkent.amplify.prompt.DefaultLayoutPromptView$SavedState$1.createFromParcel(DefaultLayoutPromptView.java:137)
       at android.os.Parcel.readParcelable(Parcel.java:2252)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2546)
       at android.os.Parcel.readSparseArray(Parcel.java:1874)
       at android.os.Parcel.readValue(Parcel.java:2209)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:822)
       at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2217)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1086)
       at com.tabe3.news.ui.activity.MainActivity.onRestoreInstanceState(MainActivity.java:805)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1027)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1174)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by stkent** [comment]
@hisham2007 should have a fix out in v1.3.1 by end of day today.

**Comment by stkent** [comment]
@hisham2007 version 1.3.1 is now deployed to jCenter with a fix for this issue; please update and let us know how you get on. Thanks!
