### ISSUE TITLE
Crashes if user doesn't interact with it

### ISSUE THREAD

**Issue by TheBachelor** [stkent/amplify#161]
If a user doesn't interact with the popup and instead goes to the next screen, when the user comes back to the initial screen, the app crashes.

**Comment by stkent** [comment]
Uh oh! Do you have a stack trace you could share? That would greatly help figure out what's going on. Thanks!

**Comment by TheBachelor** [comment]
Oh yes, it's linked the Configuration changing after the prompt is displayed, but I don't change the configuration. Please find the stack trace below

Fatal Exception: java.lang.IllegalStateException: Configuration cannot be changed after the prompt is first displayed.
       at com.github.stkent.amplify.prompt.BasePromptView.applyBaseConfig(BasePromptView.java:279)
       at com.github.stkent.amplify.prompt.BasePromptView.onRestoreInstanceState(BasePromptView.java:147)
       at com.github.stkent.amplify.prompt.DefaultLayoutPromptView.onRestoreInstanceState(DefaultLayoutPromptView.java:85)
       at android.view.View.dispatchRestoreInstanceState(View.java:16037)
       at android.view.ViewGroup.dispatchThawSelfOnly(ViewGroup.java:3450)
       at com.github.stkent.amplify.prompt.BasePromptView.dispatchRestoreInstanceState(BasePromptView.java:161)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
       at android.view.View.restoreHierarchyState(View.java:16015)
       at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1989)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:979)
       at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1670)
       at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:577)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by stkent** [comment]
Thanks, I'll take a look later today and see what I can deduce :)

**Comment by stkent** [comment]
Can you please show the code where you configure the library and prompt view? Thanks!

**Comment by TheBachelor** [comment]
Sure thing.

In my Init class that extends Application:

Amplify.initSharedInstance(this)
                .setFeedbackEmailAddress("help@abcd.io")
                .addEnvironmentBasedRule(new GooglePlayStoreRule()) 
                .applyAllDefaultRules();

Then I call the view to display in the onCreateView of a fragment:

if (savedInstanceState == null) {
            DefaultLayoutPromptView promptView = (DefaultLayoutPromptView) rootView.findViewById(R.id.prompt_view);
            Amplify.getSharedInstance().promptIfReady(promptView);
        }

**Comment by stkent** [comment]
@TheBachelor thanks! I have an idea how this might be happening, looking into it more.

**Comment by stkent** [comment]
@TheBachelor please try this version of the library in your app:

https://www.dropbox.com/s/0plkr1cl98yu9rr/amplify-161-fix.aar?dl=0

You should be able to place the `.aar` file in your `app/libs` folder, then add the following configuration in your `build.gradle` file:

```
repositories {
    flatDir {
        dirs 'libs'
    }
}
```

and replace your existing amplify `compile` dependency with

```
dependencies {
    compile(name: 'amplify-161-fix', ext: 'aar')
}
```

Let me know if that solves the issue!

If possible, it would be great to get more information on your app navigation to really nail this one down. I'm unclear on the details of this operation:

> If a user doesn't interact with the popup and instead goes to the next screen, when the user comes back to the initial screen, the app crashes.

In particular:

- I'm guessing the 'first screen' is an `Activity` with a single `Fragment` inside it? Is that `Fragment` added programmatically or in XML?
- Is the 'next screen' a whole new `Activity`, or are you pushing (and then popping) a `FragmentTransaction` onto the stack?
- Does this crash occur every time or only some of the time?

If you could provide more detailed info (or even better, a small sample app that demonstrates the issue), that would be outstanding. Cheers!

**Comment by TheBachelor** [comment]
Here's a video of what happens as I navigate: https://lookback.io/watch/Ck5JY297Ap8eA4b7i

The error that causes the crash is:

FATAL EXCEPTION: main
                                                            Process: com.giveaHi5, PID: 6403
                                                            java.lang.IllegalStateException: Configuration cannot be changed after the prompt is first displayed.
                                                                at com.github.stkent.amplify.prompt.BasePromptView.applyBaseConfig(BasePromptView.java:279)
                                                                at com.github.stkent.amplify.prompt.BasePromptView.onRestoreInstanceState(BasePromptView.java:147)
                                                                at com.github.stkent.amplify.prompt.DefaultLayoutPromptView.onRestoreInstanceState(DefaultLayoutPromptView.java:85)
                                                                at android.view.View.dispatchRestoreInstanceState(View.java:16037)
                                                                at android.view.ViewGroup.dispatchThawSelfOnly(ViewGroup.java:3450)
                                                                at com.github.stkent.amplify.prompt.BasePromptView.dispatchRestoreInstanceState(BasePromptView.java:161)
                                                                at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3436)
                                                                at android.view.View.restoreHierarchyState(View.java:16015)
                                                                at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1094)
                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:979)
                                                                at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1670)
                                                                at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:577)
                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:158)
                                                                at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by stkent** [comment]
Thanks for the video and testing - I'll have another go this coming week at fixing!

**Comment by stkent** [comment]
Ok, please try this version of the library:

https://www.dropbox.com/s/r2tghjjzv745u0d/amplify-161-fix-v2.aar?dl=0

Setup instructions are the same as before, with only the dependency name tweaked:

```
dependencies {
    compile(name: 'amplify-161-fix-v2', ext: 'aar')
}
```

Please let me know if that fixes your issue!

**Comment by TheBachelor** [comment]
The problem has been solved @stkent what was the issue? If you don't mind me asking

**Comment by stkent** [comment]
This was the problematic line:

https://github.com/stkent/amplify/blob/a4b9e7ee7a798a3952bd2e0bfc755d2c1a9f8df4/amplify/src/main/java/com/github/stkent/amplify/prompt/BasePromptView.java#L147

The protections in `applyConfig` are meant to prevent users from accidentally changing the configuration of their `PromptView` after it is already shown to the user. The protection was being triggered on state restoration too, however. I will put out a bugfix release later today and notify you when it's available on jcenter :)

**Comment by TheBachelor** [comment]
Oh I see. Well, thanks man. You're a real lifesaver!

**Comment by stkent** [comment]
@TheBachelor version 1.5.1 of amplify is now available via jcenter and includes this fix :) You are now safe to swap back to using that, and discard the AAR I sent you!
