### ISSUE TITLE
Error inflating XML

### ISSUE THREAD

**Issue by dejiapps** [stkent/amplify#166]
I keep getting this error on app start:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dejiapps.a4do/com.dejiapps.a4do.MainActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.github.stkent.amplify.prompt.DefaultLayoutPromptView

This is the layout I choose to put in my XML:

```xml
<com.github.stkent.amplify.prompt.DefaultLayoutPromptView
        android:id="@+id/prompt_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
```

I don't know what I could be doing wrong, any help will be appreciated.

**Comment by stkent** [comment]
Uh oh! When you see that `InflateException`, it's common for there to be a separate exception (the underlying cause) printed lower down in the stack trace. Could you please reply and copy in the entire stack trace from this crash? Thanks!

**Comment by dejiapps** [comment]
Wow, thanks for replying so soon. Here is the entire error message:

02-02 13:17:37.287 18136-18136/com.dejiapps.a4do E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.dejiapps.a4do, PID: 18136
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dejiapps.a4do/com.dejiapps.a4do.MainActivity}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.github.stkent.amplify.prompt.DefaultLayoutPromptView
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                                    Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.github.stkent.amplify.prompt.DefaultLayoutPromptView
                                                                    Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.github.stkent.amplify.prompt.DefaultLayoutPromptView
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                       at com.dejiapps.a4do.MainActivity.onCreate(MainActivity.java:278)
                                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                                    Caused by: java.lang.IllegalStateException: You must call initSharedInstance before calling getSharedInstance.
                                                                       at com.github.stkent.amplify.tracking.Amplify.getSharedInstance(Amplify.java:101)
                                                                       at com.github.stkent.amplify.prompt.BasePromptView.<init>(BasePromptView.java:117)
                                                                       at com.github.stkent.amplify.prompt.DefaultLayoutPromptView.<init>(DefaultLayoutPromptView.java:56)
                                                                       at com.github.stkent.amplify.prompt.DefaultLayoutPromptView.<init>(DefaultLayoutPromptView.java:48)
                                                                       at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at com.dejiapps.a4do.MainActivity.onCreate(MainActivity.java:278) 
                                                                       at android.app.Activity.performCreate(Activity.java:6679) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741) 
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6176) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by stkent** [comment]
Thanks for the full trace! It would seem that the prompt view is attempting to access the shared `Amplify` instance before that instance has been configured. Whereabouts in your app are you performing the `Amplify` initialization? It should look something like this:

```java
public class ExampleApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Amplify.initSharedInstance(this)
               .setFeedbackEmailAddress("someone@example.com")
               .applyAllDefaultRules();
    }

}
```

**Comment by dejiapps** [comment]
Its in a different class on its own, like in the test app.

**Comment by stkent** [comment]
@dejiapps r.e.

> Its in a different class on its own, like in the test app.

Is that class set as the application class for your app? Please paste your entire application class and AndroidManifest here so we can check :)

**Comment by dejiapps** [comment]
No, I'm using Sugar ORM was set as the application class. I have set Amplify as the application class and it is working now. Thanks for the library and helping me figure the issue out.

**Comment by stkent** [comment]
Glad we figured it out! Let me know if you run into any other issues. Cheers!
