### ISSUE TITLE
Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference

### ISSUE THREAD

**Issue by peterdk** [stkent/amplify#185]
I am getting a few users with this crash on 2.2.0. Don't know if 2.2.1 fixed it.

It happens in Application's onCreate() when calling Amplify.init(this);
Only on 6.0.1 strangely.

```
java.lang.RuntimeException: Unable to create application App: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4714)
        at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5421)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at com.github.stkent.amplify.tracking.Amplify.<init>(SourceFile:137)
        at com.github.stkent.amplify.tracking.Amplify.initSharedInstance(SourceFile:96)
        at com.github.stkent.amplify.tracking.Amplify.initSharedInstance(SourceFile:87)
        at SharedApp.onCreate(SourceFile:104)
        at App.onCreate(SourceFile:34)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4711)
        at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5421)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by stkent** [comment]
Hi @peterdk,

That's a weird one! This is not something that [v2.2.1](https://github.com/stkent/amplify/blob/master/CHANGELOG.md#v221) would change. A few questions:

- Are you using multidex at all?
- Are crashes limited to a specific device manufacturer?
- Are you seeing any other initialization crashes related to other libraries?
- Are you able to reproduce locally using an emulator?
- What % of your users are affected, approximately?

Let me know the answers to those questions when you're able and we'll take it from there :)

Stuart

**Comment by omprakashnitdgp** [comment]
I am also getting same error


    Process: com.lovedwealth, PID: 28758
    java.lang.RuntimeException: Unable to create application com.lovedwealth.MainApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.registerActivityLifecycleCallbacks(android.app.Application$ActivityLifecycleCallbacks)' on a null object reference
        at com.wix.reactnativeuilib.keyboardinput.AppContextHolder.setApplication(AppContextHolder.java:12)
        at com.wix.reactnativeuilib.keyboardinput.KeyboardInputPackage.<init>(KeyboardInputPackage.java:20)
        at com.facebook.react.PackageList.getPackages(PackageList.java:121)
        at com.lovedwealth.MainApplication$1.getPackages(MainApplication.java:30)
        at com.reactnativenavigation.react.NavigationReactNativeHost.createReactInstanceManager(NavigationReactNativeHost.java:50)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:38)
        at com.reactnativenavigation.react.ReactGateway.<init>(ReactGateway.java:17)
        at com.reactnativenavigation.NavigationApplication.createReactGateway(NavigationApplication.java:40)
        at com.reactnativenavigation.NavigationApplication.onCreate(NavigationApplication.java:27)
        at com.lovedwealth.MainApplication.onCreate(MainApplication.java:49)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by stkent** [comment]
Hi @omprakashnitdgp! Can you please provide answers to the following?

- Are you using multidex at all?
- Are crashes limited to a specific device manufacturer?
- Are you seeing any other initialization crashes related to other libraries?
- Are you able to reproduce locally using an emulator?
- What % of your users are affected, approximately?

Thanks!
